### ISSUE TITLE
Configurable intervals for broadcasts

### ISSUE THREAD

**Issue by TBG1000** [Warzone/mars#14]
### Issue:
Automatic broadcasts using Mars use a fixed, global unmodifiable [one minute interval](https://github.com/Warzone/mars/blob/d809e1facb40ed5dbe8c9ee0cc515f8d244efcc3/src/main/kotlin/network/warzone/mars/broadcast/BroadcastFeature.kt#L15).

### Background:
Broadcasts in TGM allowed server administrator to at least configure a [desired global interval](https://github.com/WarzoneMC/tgm/blob/efe55bae1c0ec75d449fe23ad5d2005b460c4a39/TGM/src/main/java/network/warzone/tgm/broadcast/BroadcastManager.java#L211) for any loaded broadcasts. This interval could be changed at any time from the server panel.

Currently, with Mars, only the following properties are available: `name`, `message`, `permission`, `newline`. Broadcasts are also managed from the backend (API) by manipulating the [broadcasts.yml](https://github.com/Warzone/mars-api/blob/master/src/main/resources/broadcasts.yml) file.

### Desired solution:
Server owners should have the ability to configure a default global interval for all broadcasts, as well as an individual `interval` property for each broadcast.

Example config:
```yml
global-interval: 60 # One minute
broadcasts:
- name: vip
  message: This is a VIP broadcast!
  permission: broadcasts.vip
  interval: 30 # Broadcasted every 30 seconds, overrides global setting
  newline: false
```

### Affected areas / files:
- [Broadcast](https://github.com/Warzone/mars/blob/master/src/main/kotlin/network/warzone/mars/broadcast/Broadcast.kt)
- [Broadcast feature](https://github.com/Warzone/mars/blob/master/src/main/kotlin/network/warzone/mars/broadcast/BroadcastFeature.kt)
- (API) Broadcast [model](https://github.com/Warzone/mars-api/blob/master/src/main/kotlin/database/models/Broadcast.kt)
- (API) [broadcasts.yml](https://github.com/Warzone/mars-api/blob/master/src/main/resources/broadcasts.yml)
