### ISSUE TITLE
Configurable triggerable events for broadcasts

### ISSUE THREAD

**Issue by TBG1000** [Warzone/mars#15]
### Issue:
Broadcasts are only governed by a time interval and cannot be triggered by events, but only by executing commands.

### Background:
Broadcasts in TGM allowed server administrator to configure several [events](https://github.com/WarzoneMC/tgm/blob/efe55bae1c0ec75d449fe23ad5d2005b460c4a39/TGM/src/main/java/network/warzone/tgm/broadcast/BroadcastEventTrigger.java) that triggered a broadcast.

Such events are no longer available with Mars.

### Desired solution:
Server owners should be able to specify some event(s) that will trigger the broadcast(s).
Lack of the events property would mean the broadcast is just periodically sent in accordance with the fixed global interval.

Some events extracted from [TGM](https://github.com/WarzoneMC/tgm/blob/master/TGM/src/main/java/network/warzone/tgm/broadcast/BroadcastEventTrigger.java):
- `onFirstJoin` (when the player first joins the server)
- `onJoin` (when the player joins the server)
- `onMatchResult` (when the match ends)
- `onTeamJoin` (when the player joins a team)
- `onMatchLoad` (when a match is loaded)

Example config:
```yml
- name: broadcastOnJoin
  message: This broadcast is sent every time you join the server!
  events: onJoin # Broadcast is sent to the player every time they join the server

- name: epicBroadcast
  message: This broadcast is sent every minute, but also when you first join the server!
  # This broadcast is sent when the player first joins the server, 
  # then periodically (every 1 minute according to the global broadcast interval)
  events: onFirstJoin, interval
```

### Affected areas / files:
- [Broadcast](https://github.com/Warzone/mars/blob/master/src/main/kotlin/network/warzone/mars/broadcast/Broadcast.kt)
- [Broadcast feature](https://github.com/Warzone/mars/blob/master/src/main/kotlin/network/warzone/mars/broadcast/BroadcastFeature.kt)
- (API) Broadcast [model](https://github.com/Warzone/mars-api/blob/master/src/main/kotlin/database/models/Broadcast.kt)
- (API) [broadcasts.yml](https://github.com/Warzone/mars-api/blob/master/src/main/resources/broadcasts.yml)
